### ISSUE TITLE
[feature]Let vim-unstack to parse traces in quickfix.

### ISSUE THREAD

**Issue by teto** [mattboehm/vim-unstack#25]
Hi,

Would it be possible to convert this into a compiler similar to:
https://github.com/idbrii/daveconfig/blob/master/multi/vim/compiler/python.vim

This way, one could let &makeprg="python3 something"', :run make and just use the quicklist to get through errors.

**Comment by mattboehm** [comment]
It might be, that's an interesting idea.

If I understand correctly, you could use that linked script for python now to populate the quickfix list and still use unstack to open multiple entries in that list side-by-side.

However, if your motivation is to not need that other script or to bring in support of all of unstack's supported trace formats, that would require a bit of work on my part. I would need a way to convert unstack's [regexes](https://github.com/mattboehm/vim-unstack/blob/master/autoload/unstack/extractors.vim#L27) to the errorformat format.

I suspect that there's no simple way to convert the format, so I'm trying to figure out if there's any other ways that integrating this into unstack can add value over setting the errorformat directly. Let me know if you have any thoughts on this.
