### ISSUE TITLE
Do not open files in vim split that cannot be read

### ISSUE THREAD

**Issue by IngoHeimbach** [mattboehm/vim-unstack#28]
Hey,
first thanks for your project. I often use `unstack` when developing python code and it really helps to find the cause for exceptions quickly. :+1: 
In the last few weeks I often used unstack in combination with valgrind. By default valgrind only shows filenames and no paths, so `unstack` often cannot open some files and displays empty buffers instead. Would it not be better to ignore these files completely?

**Comment by mattboehm** [comment]
Thanks, this makes sense to me. I could foresee adding an error message in the future, but for now, this is nice and simple and an improvement over the existing behavior.
